### PR TITLE
Proposed tap.py example changes

### PR DESCRIPTION
**Pull request by Sigafoos**
In response to #28

### CODE REVIEW

**Comment by tannewt** [comment]
I don't think this is what we want. `tapped` is held high for an amount of time after a detection event even if we read it. Assigned to kattni to confirm.

**Comment by kattni** [comment]
I don't think this is right either. If the example isn't working, then we need to sort it, but this isn't the fix. I haven't had a chance to test it and try to figure out the issue. I've added it to the list and I'll look into it.

**Comment by jerryneedell** [comment]
Odd. If I just set up the lis3dh  via the REPL but then just test lis3dh.tapped  I get True and False as expected. But the example does not work.

**Comment by jerryneedell** [comment]
example - before and after setting threshold - defaults seem to work 
```Adafruit CircuitPython 3.0.0-alpha.3-2-gbf42611-dirty on 2018-03-18; Adafruit CircuitPlayground Express with samd21g18
>>>
>>>
>>>
>>> import board
>>> import adafruit_lis3dh
>>>
>>> import busio
>>> i2c = busio.I2C(board.ACCELEROMETER_SCL, board.ACCELEROMETER_SDA)
>>> i2c = busio.I2C(board.ACCELEROMETER_SCL, board.ACCELEROMETER_SDA)lis3dh = adafruit_lis3dh.LIS3DH_I2C(i2c, address=0x19)
>>> lis3dh = adafruit_lis3dh.LIS3DH_I2C(i2c, address=0x19)
>>> i2c = busio.I2C(board.ACCELEROMETER_SCL, board.ACCELEROMETER_SDA)
>>> lis3dh.range = adafruit_lis3dh.RANGE_2_G
>>> lis3dh.tapped
False
>>> lis3dh.tapped
True
>>>
>>> lis3dh.tapped
False
>>> lis3dh.set_tap(2, 80)
>>> lis3dh.tapped
False
>>> lis3dh.tapped
True
>>> lis3dh.tapped
False
>>> 
```

**Comment by tannewt** [comment]
@jerryneedell When doing something on the REPL you do it much slower than the core can.

@Sigafoos you ok if we close this?

**Comment by Sigafoos** [comment]
@tannewt definitely! Do we have another solution? I'm not saying mine is right/good. But it seems like people understand it better than me, so maybe a way forward has come out of it?

**Comment by kattni** [comment]
Closing this PR. This fix isn't the right way to go about this, and doesn't seem to be consistently resolving it at the moment anyway. Will try to figure out what the issue is.

**Pull request closed without merging**
