### PR TITLE
Update spinner.py

### PR DESCRIPTION
**Pull request by ladyada**

### CODE REVIEW

**Comment by ladyada** [comment]
fix for https://github.com/adafruit/Adafruit_CircuitPython_LIS3DH/issues/46
@kevinjwalters looks good?

**Comment by kevinjwalters** [comment]
Looks good _but_ the same problem exists in examples/spinner_advanced.py which also needs the fix.

**Review by kevinjwalters — CHANGES_REQUESTED** [review]
The change is good but also needs applying to examples/spinner_advanced.py

**Comment by ladyada** [comment]
thanks will do that one next :)

**Pull request merged**
