### PR TITLE
Adding a named tuple for acceleration

### LINKED ISSUE #12: Access to single axis value
This mainly comes up in conditionals, and can currently be done like this:
```python
if lis3dh.acceleration[2] > SOME_VALUE:
    print("Z axis exceeds the value!")
```
but requires knowing the index of the axis. Is there anyway this could be done where it's more obvious what's being accessed?
Like this:
```python
if lis3dh.acceleration['Z'] > SOME_VALUE:
    print("Z axis exceeds the value!")
```
or this:
```python
if lis3dh.acceleration.Z > SOME_VALUE:
    print("Z axis exceeds the value!")
```

### PR DESCRIPTION
**Pull request by Sigafoos**
Fixes #12

### CODE REVIEW

**Comment by tannewt** [comment]
@jerryneedell or @hukuzatuna mind testing this? The code looks good to me.

**Comment by jerryneedell** [comment]
This is next on my “to do” list. Hopefully tomorrow.

**Comment by jerryneedell** [comment]
tried this on a CircuitPlayGround_express with CP 3.0-alpha - current master.
```
 Adafruit CircuitPython 3.0.0-alpha.3-2-gbf42611-dirty on 2018-03-18; Adafruit CircuitPlayground Express with samd21g18
>>> 
>>> import time
>>> import board
>>> import adafruit_lis3dh
>>> 
>>> import busio
>>> i2c = busio.I2C(board.ACCELEROMETER_SCL, board.ACCELEROMETER_SDA)
>>> lis3dh = adafruit_lis3dh.LIS3DH_I2C(i2c,address=0x19)
>>> lis3dh.range = adafruit_lis3dh.RANGE_2_G
>>> dir(lis3dh)
['__qualname__', '_write_register_byte', '_read_register', '__module__', '__init__', '_int1', '_int2', '_i2c', '_buffer']
>>> lis3dh.acceleration
acceleration(x=0.153256, y=0.0862066, z=9.93291)
>>> 
```
looks OK to me - anything in particular that needs to be checked?

Doesn't seem to break anything.  Previous test programs still run OK.

**Comment by kattni** [comment]
Thanks for testing it @jerryneedell! Approved!

**Comment by caternuson** [comment]
May want to future proof the import since there's a plan to rename the `u...` modules.

**Pull request merged**
