### PR TITLE
added gravitational constant, hopefully made it a bit easier to see w…

### PR DESCRIPTION
**Pull request by Sigafoos**
…hat was being calculated

### CODE REVIEW

**Comment by dglaude** [comment]
Maybe STANDARD_GRAVITY should be renamed to EARTH_GRAVITY. :-)

**Comment by deshipu** [comment]
> Maybe STANDARD_GRAVITY should be renamed to EARTH_GRAVITY. :-)

What do we do when it changes? I think we should also add a date, just to be sure! ;-)

**Comment by microbuilder** [comment]
This is probably my fault ... at one point I added in the gravitational constant for the Death Star, but only kept gravity on the sun and moon for the [earlier unified sensor API](https://github.com/adafruit/Adafruit_Sensor/blob/master/Adafruit_Sensor.h#L34). The [Death Star gravitational constant estimate](https://developer.android.com/reference/android/hardware/SensorManager.html#GRAVITY_DEATH_STAR_I) was buried in the low level sensor API source code for Android, which I used as a reference for the typedefs in the first draft of the sensor API. :) I just figured it might be fun to let people simulate gravity on the moon, etc., but I doubt anyone has actually used this.

**Review by tannewt — APPROVED** [review]
This looks fine to me! We can always change it when someone uses it on the moon.

**Pull request merged**
