### PR TITLE
Updating library vs Datasheet

### PR DESCRIPTION
**Pull request by jposada202020**
In doing some work to add type annotations I come across the difference between the library and the datasheet. Not sure if this is intentional or not, so if so please disregard this PR. I would work in the type annotatios afterwards. Thanks

**information source:**
https://cdn-shop.adafruit.com/datasheets/LIS3DHappnote.pdf
image

### CODE REVIEW

**Comment by tekktrik** [comment]
Looking into this, I think a found [another datasheet](https://www.st.com/resource/en/datasheet/cd00274221.pdf) that explains this discrepancy.

**Comment by tekktrik** [comment]
Looking on ST's website, it looks like the documentation is now different than what you've provided from the Adafruit page, and reflects the existing code.  I'm not quite sure whether the update was for clarification (the numbers were nice and round before as opposed to the truth to which they've been updated), or whether there actually WAS a change (some revision update).

**Comment by tekktrik** [comment]
My guess is the former, but it may be worth inquiring, I can handle that.

**Comment by jposada202020** [comment]
Thanks to take a look into this. Will work in the type annotations then, this PR will be easily incorporated once we know the real reason. looking in table 15 from the Adafruit source, I think you are probably right.

**Comment by tcfranks** [comment]
@jposada202020 nice work on the type annotations!  adding @tekktrik to this, will this pr now be cancelled / withdrawn?  I noticed (I had started work on the annotations, without realizing I was in parallel) that the docstrings need work.  The base class incorrectly identifies the interrupt pins, one of whish should be stated that it exists only on the stemmaQT model, and the SPI sublclass docstring is an incorrectly modified cut/paste of the I2C docstring.

@jposada202020  I yield to you if you want to pursue this, or if you like I'd be happy to pursue it.  I just didn't want to complicate things by coming in over this PR

**Comment by jposada202020** [comment]
@tcfranks Hello :). PR is still ongoing as Tekktrik is reviewing two conflicting Data-sheet. Please do work on correcting the docstrings. This PR could/would be cancelled once we no what is the correct information that we need to put in the Docstring but I could create another PR afterwards, no worries :) and congrats in your 💯 PRs

**Pull request closed without merging**
